/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: ['./src/**/*.{html,js,svelte,ts}'],
    theme: {
        extend: {
            colors: {
                "secondary-fixed-dim": "#bec9bf",
                "secondary-fixed": "#dae5db",
                "on-primary-fixed-variant": "#324d39",
                "on-primary-fixed": "#062010",
                "primary-container": "#445f4a",
                "on-tertiary-container": "#b7d7c0",
                "on-surface-variant": "#c3c8c1",
                "secondary": "#bec9bf",
                "surface-dim": "#121412",
                "error-container": "#93000a",
                "error": "#ffb4ab",
                "tertiary": "#aeceb7",
                "surface-container-high": "#282a28",
                "surface-tint": "#b0ceb4",
                "on-tertiary-fixed": "#042012",
                "on-error": "#690005",
                "surface-bright": "#383a37",
                "on-primary": "#1c3624",
                "inverse-surface": "#e2e3df",
                "surface-container": "#1e201e",
                "surface-container-lowest": "#0d0f0d",
                "inverse-on-surface": "#2f312f",
                "background": "#121412",
                "on-secondary-container": "#b3bfb5",
                "tertiary-fixed": "#caead2",
                "on-surface": "#e2e3df",
                "tertiary-container": "#425f4c",
                "on-background": "#e2e3df",
                "surface-variant": "#333533",
                "on-tertiary-fixed-variant": "#304d3b",
                "primary": "#b0ceb4",
                "secondary-container": "#444e46",
                "on-primary-container": "#b9d7bd",
                "primary-fixed": "#ccead0",
                "on-secondary-fixed-variant": "#3f4942",
                "surface": "#121412",
                "primary-fixed-dim": "#b0ceb4",
                "on-tertiary": "#1a3626",
                "surface-container-highest": "#333533",
                "on-secondary": "#29332c",
                "tertiary-fixed-dim": "#aeceb7",
                "outline": "#8d928c",
                "inverse-primary": "#4a6550",
                "on-secondary-fixed": "#141e17",
                "on-error-container": "#ffdad6",
                "surface-container-low": "#1a1c1a",
                "outline-variant": "#434843",
                "moss-dark": "#4A5D4E"
            },
            fontFamily: {
                "headline": ["Space Grotesk", "sans-serif"],
                "body": ["Inter", "sans-serif"],
                "label": ["Inter", "sans-serif"]
            },
            borderRadius: { "DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px" },
            animation: {
                'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
            }
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/container-queries'),
    ],
}
